### ISSUE TITLE
Timing and stakeholder involvement in the standards process, as well as use-it-or-lose-it

### ISSUE THREAD

**Issue by elear** [mnot/avoiding-internet-centralization#35]
Is it worth asking the question about how to bring in a broader swathe of stakeholders such that the standards can be developed that allow for both flexibility **and** interoperability?  For instance, how might we get a selection of new entrants and entrenched players to play together?  My personal observations at M3AAWG lead me to believe that this may be a **very** hard problem, but the IETF seems to do its best work when you have a good mix of operators and developers (made easy when we're in the space of devops ;-)

Similarly, are there RFC 9170 issues hiding here that also need to be considered when it comes to centralization?

**Comment by mnot** [comment]
> Is it worth asking the question about how to bring in a broader swathe of stakeholders such that the standards can be developed that allow for both flexibility and interoperability? For instance, how might we get a selection of new entrants and entrenched players to play together? My personal observations at M3AAWG lead me to believe that this may be a very hard problem, but the IETF seems to do its best work when you have a good mix of operators and developers (made easy when we're in the space of devops ;-)

I feel like this would be overreaching for this spec - these issues deserve separate consideration, and centralisation is just one aspect. I really want to resist this draft becoming a sink for _all_ of the issues that face the Internet (even if many do relate to centralization in some fashion).

> Similarly, are there RFC 9170 issues hiding here that also need to be considered when it comes to centralization?

6.5 touches on that lightly, and IIRC I previously had more text around this, but removed it because it didn't seem well-supported (and again, it didn't seem central to the arguments the draft was making).

I'm inclined to close this; if you feel there's more to discuss here say so and I'll reopen.
