### ISSUE TITLE
Spend a little time more time up front on centralization risk

### ISSUE THREAD

**Issue by elear** [mnot/avoiding-internet-centralization#39]
Given that you use the term "centralization risk" throughout your draft, I think you should spend a bit more time defining it on first use.  E.g., something like, the likelihood of most people using one or a small number of providers for the same service (or some such).

**Comment by elear** [comment]
Linked to #38

**Comment by mnot** [comment]
Section 2 is the definition; I'm not sure if you saw that (or if it existed) when you opened this issue. Are you asking for more definition, or more examples?

So far I've shied away from using too many examples, because a) I don't want to pick on any project/protocol specifically too much, and b) I want the document to be relevant for a reasonably long amount of time. 

Neither of those is strong pushback on examples, provided we find the right ones. If you want more examples, some suggestions would be be most welcome.

**Comment by elear** [comment]
I agree.  In rereading my own comment, I'm actually happy with the text as it is in this context.
