### ISSUE TITLE
What would you like to see by way of future work?

### ISSUE THREAD

**Issue by elear** [mnot/avoiding-internet-centralization#44]
I think this document screams for a call-to-action and a summary.  As you put such a thing together, it will help to observe an adage one of my friends lives by:

1. Say what you're going to say (abstract)
2. Say it (most of the body)
3. Say what you said (summary) and what you want to have happen next (call to action)

**Comment by mnot** [comment]
I don't know the this *is* a 'call to action' kind of document -- it's more explaining the landscape and particular consequence s of it. Beyond the 'what can standards do' section, I'm not sure there _is_ a "next".

**Comment by mnot** [comment]
More specifically -- what do _you_ think the CtA should be?

**Comment by elear** [comment]
Here are a few possibilities from which to choose:

- When developing a protocol, ask these questions (and then some questions {think checklist}) 
- The community, the including {IAB, IRTF, others}, is invited to consider this matter in more depth, especially in regards to (specific technologies that might help avoid concentration)
- Further measurements of the risk of centralization a'la [cite Aqsa's wonderful ANRP paper] are invited..

But don't forget to summarize well what you said first ;-)

**Comment by elear** [comment]
By the way, those are only suggestions.  You should be comfortable with whatever approach you would like to take.

**Comment by mnot** [comment]
I'm not really on board with those --

* a checklist is going to be incredibly difficult to create for every internet protocol - by nature, much of this is specific to the market/environment the protocol operates within
* I don't know that a call for specific tech to avoid concentration is really realistic; if it emerges that's great but hope is not...
* I'm less than enthusiastic about measurement activities, because it's not really clear how they're actionable, or often even if the metric is appropriate

**Comment by elear** [comment]
That's ok!  But there must be something you want the community to do, even if it's just considering the document as they're developing specifications.  Anyway, my suggestion is that you consider this as you're developing the rest of doc.

**Comment by mnot** [comment]
I think what I want the community to do is captured (imperfectly) in 'what can standard efforts do?'

Is there something I can do to make it clearer?
