### ISSUE TITLE
Extensibility and maintenance

### ISSUE THREAD

**Issue by huitema** [mnot/avoiding-internet-centralization#48]
The "Over-Extensibility" section points out the risks of designs that only specify a narrow core of functions and rely on extensibility to meet actual demand. That's a great point, but the text only addresses the initial design of the protocol. I wonder whether the text should be extended to something like "protocol gardening". Gardeners will shape trees as they grow by pruning them. Should standard bodies similarly bring extensions inside the core of a new revision, or prune (and prohibit) extensions that demonstrate too much centralization risks?

**Comment by mnot** [comment]
@huitema PTAL.

I think this is part of a larger point that I'm trying to make -- standards efforts should continue to push the 'waterline' of what's open and interoperable up, rather than allowing it to be claimed as proprietary. There's a dynamic in [this comment](https://github.com/mnot/avoiding-internet-centralization/issues/32#issuecomment-1129472920) that I'm still trying to capture in the document.

Regarding - 'prune extensions' -- how would we do that?

Am closing, but please request reopening if you feel I haven't adequately addressed.
