### ISSUE TITLE
Kinds of centralisation

### ISSUE THREAD

**Issue by mnot** [mnot/avoiding-internet-centralization#69]
A few people (eg @mallory, @mirjak) have mentioned that 2.2 is framed as a taxonomy, and as a result isn't helpful.

Mallory suggests 'centralizing forces' -- thoughts?

**Comment by mirjak** [comment]
I think 'centralizing forces' is definitely better but it also sounds very negative to me. However, not all reasons to centralise are "bad" or "forced". Sometimes it's a good and on-purpose decision to centralise something, e.g. to increase security. Maybe "centralisation causes" or something like that is more neutral?

**Comment by jariarkko** [comment]
I agree with both comments (the original one and Mirja's)

**Comment by mnot** [comment]
See also discussion in #60

**Comment by mnot** [comment]
Trying 'Contributors to Centralization' - PTAL @jariarkko @mallory @mirjak @tfpauly

**Comment by mallory** [comment]
Centralising factors?

The headings are still reading to me as a taxonomy which is going to mean the same comment is brought up again and again, and especially when policy folks read it. 

Maybe the headings need to be longer so as not to sound taxonomic.

**Comment by mnot** [comment]
The problem is that these names are referred to throughout the paper to refer to different effects and situations, so changing the titles would be quite invasive. For internal purposes, it *is* somewhat of a taxonomy, and the rewrite to completely remove that would be quite extensive, and also go against a lot of the feedback previously received that suggested the different sections have deeper ties.

I've already passed this in front of many policy people and am not getting any negative reaction along these lines, FWIW.

Back to the suggestion -- I don't think 'factors' fits either. How about 'aspects of centralization'? Or 'facets'? If that's combined with an explicit statement that this isn't a complete taxonomy, just a collection of aspects, would that address this concern?

**Comment by mallory** [comment]
Aspects or factors works for me. Characteristics might be another. Where aspect/factor implicates the perspective of the viewer, characteristic feels more objective.

**Comment by mirjak** [comment]
I do like this conditions or enabling factors approach as discussed in #60 (or contributors seems also okay as you have it right now in the editor's copy). Because I think what you describe is really more about the root causes for centralisation than different "kinds" of centralisation. Kinds of centralisation would be for me more if you e.g. describe different technical form of the centralisation itself e.g. because it happens on different layers... I so I would say what you do is defining some terminology that you can used rather than actually creating a taxonomy (which at least to me has a certain requirement on completeness and non-overlapping separation).

**Comment by mnot** [comment]
None of those seemed quite right, so I dodged it -- see [1ed5102](https://github.com/mnot/avoiding-internet-centralization/commit/1ed5102858ccf9a1e6e37f87dd6a25357c33644e)
